version: '3'

tasks:
  do:
    watch: true
    method: timestamp
    vars:
      DIR: 'src/{{.CLI_ARGS}}'
    sources:
      - '{{.DIR}}/*'
    cmds:
      - clear
      - gcc -o bin/{{.DIR}} {{.DIR}}/main.c $(find {{.DIR}} -name '*.c' | grep -v "main.c")
      - ./bin/{{.DIR}}
